FROM postgres:17

RUN apt-get update && apt-get install -y \
    git \
    make \
    gcc \
    postgresql-server-dev-17 \
    postgresql-contrib-17

# Install pgvector
RUN git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git && \
    cd pgvector && make && make install && \
    cd .. && rm -rf pgvector

RUN apt-get remove -y git make gcc && apt-get autoremove -y && apt-get clean