/**
 * TAX REGIME DEFINITIONS
 * Each regime contains: localId, peppolCode, rate, display, legalRef, legalText, matcher
 */
export const TAX_REGIMES = {
    LV_STANDARD: {
        id: "LV_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 21,
        display: "VAT 21%",
        description: "21% VAT - standard rate in Latvia",
        legalRef: null,
        legalText: null,
        country: "LV",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    LV_REDUCED_12: {
        id: "LV_REDUCED_12",
        localId: "RED12",
        peppolCode: "AA",
        rate: 12,
        display: "VAT 12%",
        description: "12% VAT - reduced rate in Latvia",
        legalRef: null,
        legalText: null,
        country: "LV",
        matcher: (id) => id === "RED12",
    },
    LV_REDUCED_5: {
        id: "LV_REDUCED_5",
        localId: "RED5",
        peppolCode: "AA",
        rate: 5,
        display: "VAT 5%",
        description: "5% VAT - reduced rate in Latvia",
        legalRef: null,
        legalText: null,
        country: "LV",
        matcher: (id) => id === "RED5",
    },
    LV_RC_CONSTRUCTION: {
        id: "LV_RC_CONSTRUCTION",
        localId: "0000",
        peppolCode: "AE",
        rate: 0,
        display: "ANM",
        description: "Reverse charge - construction services as per Art. 142",
        legalRef: "142",
        legalText: () => "Reverse charge (Art. 142 - Construction)",
        country: "LV",
        requiresVAT: true,
        matcher: (id) => id === "0000",
    },
    LV_RC_GENERAL: {
        id: "LV_RC_GENERAL",
        localId: "143",
        peppolCode: "AE",
        rate: 0,
        display: "ANM",
        description: "Reverse charge - general as per Art. 143",
        legalRef: "143",
        legalText: () => "Reverse charge (Art. 143)",
        country: "LV",
        requiresVAT: true,
        matcher: (id) => id === "143" || id?.includes("143."),
    },
    LV_RC_METAL: {
        id: "LV_RC_METAL",
        localId: "MET",
        peppolCode: "AE",
        rate: 0,
        display: "ANM",
        description: "Reverse charge - metal processing as per Art. 143.1",
        legalRef: "143.1",
        legalText: () => "Reverse charge (Art. 143.1 - Metal processing)",
        country: "LV",
        requiresVAT: true,
        matcher: (id) => id?.includes("MET"),
    },
    LV_RC_DATA: {
        id: "LV_RC_DATA",
        localId: "DAT",
        peppolCode: "AE",
        rate: 0,
        display: "ANM",
        description: "Reverse charge - data processing as per Art. 143.1",
        legalRef: "143.1",
        legalText: () => "Reverse charge (Art. 143.1 - Data processing)",
        country: "LV",
        requiresVAT: true,
        matcher: (id) => id?.includes("DAT"),
    },
    LV_RC_SPECIFIC: {
        id: "LV_RC_SPECIFIC",
        localId: "7216",
        peppolCode: "AE",
        rate: 0,
        display: "ANM / 7216",
        description: "Reverse charge - specific goods as per Art. 143.4",
        legalRef: "143.4",
        legalText: () => "Reverse charge (Art. 143.4)",
        country: "LV",
        requiresVAT: true,
        matcher: (id) => id === "7216",
    },

    EE_STANDARD: {
        id: "EE_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 24,
        display: "VAT 24%",
        description: "24% VAT - standard rate in Estonia (from 1 July 2025)",
        legalRef: "KMS §15",
        legalText: () => "Standard VAT rate in Estonia",
        country: "EE",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    EE_REDUCED_13: {
        id: "EE_REDUCED_13",
        localId: "RED13",
        peppolCode: "AA",
        rate: 13,
        display: "VAT 13%",
        description: "13% VAT - reduced rate in Estonia",
        legalRef: "KMS §15",
        legalText: () => "Reduced VAT rate (13%) in Estonia",
        country: "EE",
        matcher: (id) => id === "RED13",
    },
    EE_REDUCED_9: {
        id: "EE_REDUCED_9",
        localId: "RED9",
        peppolCode: "AA",
        rate: 9,
        display: "VAT 9%",
        description: "9% VAT - reduced rate in Estonia",
        legalRef: "KMS §15",
        legalText: () => "Reduced VAT rate (9%) in Estonia",
        country: "EE",
        matcher: (id) => id === "RED9",
    },

    LT_STANDARD: {
        id: "LT_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 21,
        display: "VAT 21%",
        description: "21% VAT - standard rate in Lithuania",
        legalRef: "PVMĮ 19 str.",
        legalText: () => "Standard VAT rate in Lithuania",
        country: "LT",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    LT_REDUCED_12: {
        id: "LT_REDUCED_12",
        localId: "RED12",
        peppolCode: "AA",
        rate: 12,
        display: "VAT 12%",
        description: "12% VAT - reduced rate in Lithuania (from 1 January 2026)",
        legalRef: "PVMĮ 19 str.",
        legalText: () => "Reduced VAT rate (12%) in Lithuania",
        country: "LT",
        matcher: (id) => id === "RED12",
    },
    LT_REDUCED_5: {
        id: "LT_REDUCED_5",
        localId: "RED5",
        peppolCode: "AA",
        rate: 5,
        display: "VAT 5%",
        description: "5% VAT - reduced rate in Lithuania",
        legalRef: "PVMĮ 19 str.",
        legalText: () => "Reduced VAT rate (5%) in Lithuania",
        country: "LT",
        matcher: (id) => id === "RED5",
    },

    AT_STANDARD: { id: "AT_STANDARD", localId: "", peppolCode: "S", rate: 20, display: "VAT 20%", description: "20% VAT - standard rate in Austria", legalRef: null, legalText: () => "Standard VAT rate (BMF Austria)", country: "AT", matcher: (id) => id === null || id === undefined || id === "" },
    AT_REDUCED_10: { id: "AT_REDUCED_10", localId: "RED10", peppolCode: "AA", rate: 10, display: "VAT 10%", description: "10% VAT - reduced rate in Austria", legalRef: null, legalText: () => "Reduced VAT rate (BMF Austria)", country: "AT", matcher: (id) => id === "RED10" },
    AT_REDUCED_13: { id: "AT_REDUCED_13", localId: "RED13", peppolCode: "AA", rate: 13, display: "VAT 13%", description: "13% VAT - reduced rate in Austria", legalRef: null, legalText: () => "Reduced VAT rate (BMF Austria)", country: "AT", matcher: (id) => id === "RED13" },

    BE_STANDARD: { id: "BE_STANDARD", localId: "", peppolCode: "S", rate: 21, display: "VAT 21%", description: "21% VAT - standard rate in Belgium", legalRef: null, legalText: () => "Standard VAT rate (FPS Finance Belgium)", country: "BE", matcher: (id) => id === null || id === undefined || id === "" },
    BE_REDUCED_6: { id: "BE_REDUCED_6", localId: "RED6", peppolCode: "AA", rate: 6, display: "VAT 6%", description: "6% VAT - reduced rate in Belgium", legalRef: null, legalText: () => "Reduced VAT rate (FPS Finance Belgium)", country: "BE", matcher: (id) => id === "RED6" },
    BE_REDUCED_12: { id: "BE_REDUCED_12", localId: "RED12", peppolCode: "AA", rate: 12, display: "VAT 12%", description: "12% VAT - reduced rate in Belgium", legalRef: null, legalText: () => "Reduced VAT rate (FPS Finance Belgium)", country: "BE", matcher: (id) => id === "RED12" },

    BG_STANDARD: { id: "BG_STANDARD", localId: "", peppolCode: "S", rate: 20, display: "VAT 20%", description: "20% VAT - standard rate in Bulgaria", legalRef: null, legalText: () => "Standard VAT rate (NRA Bulgaria)", country: "BG", matcher: (id) => id === null || id === undefined || id === "" },
    BG_REDUCED_9: { id: "BG_REDUCED_9", localId: "RED9", peppolCode: "AA", rate: 9, display: "VAT 9%", description: "9% VAT - reduced rate in Bulgaria", legalRef: null, legalText: () => "Reduced VAT rate (NRA Bulgaria)", country: "BG", matcher: (id) => id === "RED9" },

    HR_STANDARD: { id: "HR_STANDARD", localId: "", peppolCode: "S", rate: 25, display: "VAT 25%", description: "25% VAT - standard rate in Croatia", legalRef: null, legalText: () => "Standard VAT rate (Tax Administration Croatia)", country: "HR", matcher: (id) => id === null || id === undefined || id === "" },
    HR_REDUCED_5: { id: "HR_REDUCED_5", localId: "RED5", peppolCode: "AA", rate: 5, display: "VAT 5%", description: "5% VAT - reduced rate in Croatia", legalRef: null, legalText: () => "Reduced VAT rate (Tax Administration Croatia)", country: "HR", matcher: (id) => id === "RED5" },
    HR_REDUCED_13: { id: "HR_REDUCED_13", localId: "RED13", peppolCode: "AA", rate: 13, display: "VAT 13%", description: "13% VAT - reduced rate in Croatia", legalRef: null, legalText: () => "Reduced VAT rate (Tax Administration Croatia)", country: "HR", matcher: (id) => id === "RED13" },

    CY_STANDARD: { id: "CY_STANDARD", localId: "", peppolCode: "S", rate: 19, display: "VAT 19%", description: "19% VAT - standard rate in Cyprus", legalRef: null, legalText: () => "Standard VAT rate (Tax Department Cyprus)", country: "CY", matcher: (id) => id === null || id === undefined || id === "" },
    CY_REDUCED_5: { id: "CY_REDUCED_5", localId: "RED5", peppolCode: "AA", rate: 5, display: "VAT 5%", description: "5% VAT - reduced rate in Cyprus", legalRef: null, legalText: () => "Reduced VAT rate (Tax Department Cyprus)", country: "CY", matcher: (id) => id === "RED5" },
    CY_REDUCED_9: { id: "CY_REDUCED_9", localId: "RED9", peppolCode: "AA", rate: 9, display: "VAT 9%", description: "9% VAT - reduced rate in Cyprus", legalRef: null, legalText: () => "Reduced VAT rate (Tax Department Cyprus)", country: "CY", matcher: (id) => id === "RED9" },

    CZ_STANDARD: { id: "CZ_STANDARD", localId: "", peppolCode: "S", rate: 21, display: "VAT 21%", description: "21% VAT - standard rate in Czech Republic", legalRef: null, legalText: () => "Standard VAT rate (Financial Administration Czechia)", country: "CZ", matcher: (id) => id === null || id === undefined || id === "" },
    CZ_REDUCED_10: { id: "CZ_REDUCED_10", localId: "RED10", peppolCode: "AA", rate: 10, display: "VAT 10%", description: "10% VAT - reduced rate in Czech Republic", legalRef: null, legalText: () => "Reduced VAT rate (Financial Administration Czechia)", country: "CZ", matcher: (id) => id === "RED10" },
    CZ_REDUCED_15: { id: "CZ_REDUCED_15", localId: "RED15", peppolCode: "AA", rate: 15, display: "VAT 15%", description: "15% VAT - reduced rate in Czech Republic", legalRef: null, legalText: () => "Reduced VAT rate (Financial Administration Czechia)", country: "CZ", matcher: (id) => id === "RED15" },

    DK_STANDARD: { id: "DK_STANDARD", localId: "", peppolCode: "S", rate: 25, display: "VAT 25%", description: "25% VAT - standard rate in Denmark", legalRef: null, legalText: () => "Standard VAT rate (Skattestyrelsen Denmark)", country: "DK", matcher: (id) => id === null || id === undefined || id === "" },

    FI_STANDARD: { id: "FI_STANDARD", localId: "", peppolCode: "S", rate: 25.5, display: "VAT 25.5%", description: "25.5% VAT - standard rate in Finland", legalRef: null, legalText: () => "Standard VAT rate (Vero Finland)", country: "FI", matcher: (id) => id === null || id === undefined || id === "" },
    FI_REDUCED_10: { id: "FI_REDUCED_10", localId: "RED10", peppolCode: "AA", rate: 10, display: "VAT 10%", description: "10% VAT - reduced rate in Finland", legalRef: null, legalText: () => "Reduced VAT rate (Vero Finland)", country: "FI", matcher: (id) => id === "RED10" },
    FI_REDUCED_14: { id: "FI_REDUCED_14", localId: "RED14", peppolCode: "AA", rate: 14, display: "VAT 14%", description: "14% VAT - reduced rate in Finland", legalRef: null, legalText: () => "Reduced VAT rate (Vero Finland)", country: "FI", matcher: (id) => id === "RED14" },

    FR_STANDARD: { id: "FR_STANDARD", localId: "", peppolCode: "S", rate: 20, display: "VAT 20%", description: "20% VAT - standard rate in France", legalRef: null, legalText: () => "Standard VAT rate (DGFiP France)", country: "FR", matcher: (id) => id === null || id === undefined || id === "" },
    FR_REDUCED_5_5: { id: "FR_REDUCED_5_5", localId: "RED5_5", peppolCode: "AA", rate: 5.5, display: "VAT 5.5%", description: "5.5% VAT - reduced rate in France", legalRef: null, legalText: () => "Reduced VAT rate (DGFiP France)", country: "FR", matcher: (id) => id === "RED5_5" || id === "RED5.5" },
    FR_REDUCED_10: { id: "FR_REDUCED_10", localId: "RED10", peppolCode: "AA", rate: 10, display: "VAT 10%", description: "10% VAT - reduced rate in France", legalRef: null, legalText: () => "Reduced VAT rate (DGFiP France)", country: "FR", matcher: (id) => id === "RED10" },

    DE_STANDARD: { id: "DE_STANDARD", localId: "", peppolCode: "S", rate: 19, display: "VAT 19%", description: "19% VAT - standard rate in Germany", legalRef: null, legalText: () => "Standard VAT rate (BZSt Germany)", country: "DE", matcher: (id) => id === null || id === undefined || id === "" },
    DE_REDUCED_7: { id: "DE_REDUCED_7", localId: "RED7", peppolCode: "AA", rate: 7, display: "VAT 7%", description: "7% VAT - reduced rate in Germany", legalRef: null, legalText: () => "Reduced VAT rate (BZSt Germany)", country: "DE", matcher: (id) => id === "RED7" },

    GR_STANDARD: { id: "GR_STANDARD", localId: "", peppolCode: "S", rate: 24, display: "VAT 24%", description: "24% VAT - standard rate in Greece", legalRef: null, legalText: () => "Standard VAT rate (AADE Greece)", country: "GR", matcher: (id) => id === null || id === undefined || id === "" },
    GR_REDUCED_6: { id: "GR_REDUCED_6", localId: "RED6", peppolCode: "AA", rate: 6, display: "VAT 6%", description: "6% VAT - reduced rate in Greece", legalRef: null, legalText: () => "Reduced VAT rate (AADE Greece)", country: "GR", matcher: (id) => id === "RED6" },
    GR_REDUCED_13: { id: "GR_REDUCED_13", localId: "RED13", peppolCode: "AA", rate: 13, display: "VAT 13%", description: "13% VAT - reduced rate in Greece", legalRef: null, legalText: () => "Reduced VAT rate (AADE Greece)", country: "GR", matcher: (id) => id === "RED13" },

    HU_STANDARD: { id: "HU_STANDARD", localId: "", peppolCode: "S", rate: 27, display: "VAT 27%", description: "27% VAT - standard rate in Hungary", legalRef: null, legalText: () => "Standard VAT rate (NAV Hungary)", country: "HU", matcher: (id) => id === null || id === undefined || id === "" },
    HU_REDUCED_5: { id: "HU_REDUCED_5", localId: "RED5", peppolCode: "AA", rate: 5, display: "VAT 5%", description: "5% VAT - reduced rate in Hungary", legalRef: null, legalText: () => "Reduced VAT rate (NAV Hungary)", country: "HU", matcher: (id) => id === "RED5" },
    HU_REDUCED_18: { id: "HU_REDUCED_18", localId: "RED18", peppolCode: "AA", rate: 18, display: "VAT 18%", description: "18% VAT - reduced rate in Hungary", legalRef: null, legalText: () => "Reduced VAT rate (NAV Hungary)", country: "HU", matcher: (id) => id === "RED18" },

    IE_STANDARD: { id: "IE_STANDARD", localId: "", peppolCode: "S", rate: 23, display: "VAT 23%", description: "23% VAT - standard rate in Ireland", legalRef: null, legalText: () => "Standard VAT rate (Revenue Ireland)", country: "IE", matcher: (id) => id === null || id === undefined || id === "" },
    IE_REDUCED_9: { id: "IE_REDUCED_9", localId: "RED9", peppolCode: "AA", rate: 9, display: "VAT 9%", description: "9% VAT - reduced rate in Ireland", legalRef: null, legalText: () => "Reduced VAT rate (Revenue Ireland)", country: "IE", matcher: (id) => id === "RED9" },
    IE_REDUCED_13_5: { id: "IE_REDUCED_13_5", localId: "RED13_5", peppolCode: "AA", rate: 13.5, display: "VAT 13.5%", description: "13.5% VAT - reduced rate in Ireland", legalRef: null, legalText: () => "Reduced VAT rate (Revenue Ireland)", country: "IE", matcher: (id) => id === "RED13_5" || id === "RED13.5" },

    IT_STANDARD: { id: "IT_STANDARD", localId: "", peppolCode: "S", rate: 22, display: "VAT 22%", description: "22% VAT - standard rate in Italy", legalRef: null, legalText: () => "Standard VAT rate (Agenzia delle Entrate)", country: "IT", matcher: (id) => id === null || id === undefined || id === "" },
    IT_REDUCED_4: { id: "IT_REDUCED_4", localId: "RED4", peppolCode: "AA", rate: 4, display: "VAT 4%", description: "4% VAT - reduced rate in Italy", legalRef: null, legalText: () => "Reduced VAT rate (Agenzia delle Entrate)", country: "IT", matcher: (id) => id === "RED4" },
    IT_REDUCED_5: { id: "IT_REDUCED_5", localId: "RED5", peppolCode: "AA", rate: 5, display: "VAT 5%", description: "5% VAT - reduced rate in Italy", legalRef: null, legalText: () => "Reduced VAT rate (Agenzia delle Entrate)", country: "IT", matcher: (id) => id === "RED5" },
    IT_REDUCED_10: { id: "IT_REDUCED_10", localId: "RED10", peppolCode: "AA", rate: 10, display: "VAT 10%", description: "10% VAT - reduced rate in Italy", legalRef: null, legalText: () => "Reduced VAT rate (Agenzia delle Entrate)", country: "IT", matcher: (id) => id === "RED10" },

    LU_STANDARD: { id: "LU_STANDARD", localId: "", peppolCode: "S", rate: 17, display: "VAT 17%", description: "17% VAT - standard rate in Luxembourg", legalRef: null, legalText: () => "Standard VAT rate (Administration de l'enregistrement Luxembourg)", country: "LU", matcher: (id) => id === null || id === undefined || id === "" },
    LU_REDUCED_8: { id: "LU_REDUCED_8", localId: "RED8", peppolCode: "AA", rate: 8, display: "VAT 8%", description: "8% VAT - reduced rate in Luxembourg", legalRef: null, legalText: () => "Reduced VAT rate (Administration de l'enregistrement Luxembourg)", country: "LU", matcher: (id) => id === "RED8" },
    LU_REDUCED_14: { id: "LU_REDUCED_14", localId: "RED14", peppolCode: "AA", rate: 14, display: "VAT 14%", description: "14% VAT - reduced rate in Luxembourg", legalRef: null, legalText: () => "Reduced VAT rate (Administration de l'enregistrement Luxembourg)", country: "LU", matcher: (id) => id === "RED14" },

    MT_STANDARD: { id: "MT_STANDARD", localId: "", peppolCode: "S", rate: 18, display: "VAT 18%", description: "18% VAT - standard rate in Malta", legalRef: null, legalText: () => "Standard VAT rate (Commissioner for Revenue Malta)", country: "MT", matcher: (id) => id === null || id === undefined || id === "" },
    MT_REDUCED_5: { id: "MT_REDUCED_5", localId: "RED5", peppolCode: "AA", rate: 5, display: "VAT 5%", description: "5% VAT - reduced rate in Malta", legalRef: null, legalText: () => "Reduced VAT rate (Commissioner for Revenue Malta)", country: "MT", matcher: (id) => id === "RED5" },
    MT_REDUCED_7: { id: "MT_REDUCED_7", localId: "RED7", peppolCode: "AA", rate: 7, display: "VAT 7%", description: "7% VAT - reduced rate in Malta", legalRef: null, legalText: () => "Reduced VAT rate (Commissioner for Revenue Malta)", country: "MT", matcher: (id) => id === "RED7" },

    NL_STANDARD: { id: "NL_STANDARD", localId: "", peppolCode: "S", rate: 21, display: "VAT 21%", description: "21% VAT - standard rate in Netherlands", legalRef: null, legalText: () => "Standard VAT rate (Belastingdienst Netherlands)", country: "NL", matcher: (id) => id === null || id === undefined || id === "" },
    NL_REDUCED_9: { id: "NL_REDUCED_9", localId: "RED9", peppolCode: "AA", rate: 9, display: "VAT 9%", description: "9% VAT - reduced rate in Netherlands", legalRef: null, legalText: () => "Reduced VAT rate (Belastingdienst Netherlands)", country: "NL", matcher: (id) => id === "RED9" },

    PL_STANDARD: { id: "PL_STANDARD", localId: "", peppolCode: "S", rate: 23, display: "VAT 23%", description: "23% VAT - standard rate in Poland", legalRef: null, legalText: () => "Standard VAT rate (KAS Poland)", country: "PL", matcher: (id) => id === null || id === undefined || id === "" },
    PL_REDUCED_5: { id: "PL_REDUCED_5", localId: "RED5", peppolCode: "AA", rate: 5, display: "VAT 5%", description: "5% VAT - reduced rate in Poland", legalRef: null, legalText: () => "Reduced VAT rate (KAS Poland)", country: "PL", matcher: (id) => id === "RED5" },
    PL_REDUCED_8: { id: "PL_REDUCED_8", localId: "RED8", peppolCode: "AA", rate: 8, display: "VAT 8%", description: "8% VAT - reduced rate in Poland", legalRef: null, legalText: () => "Reduced VAT rate (KAS Poland)", country: "PL", matcher: (id) => id === "RED8" },

    PT_STANDARD: { id: "PT_STANDARD", localId: "", peppolCode: "S", rate: 23, display: "VAT 23%", description: "23% VAT - standard rate in Portugal", legalRef: null, legalText: () => "Standard VAT rate (Autoridade Tributaria Portugal)", country: "PT", matcher: (id) => id === null || id === undefined || id === "" },
    PT_REDUCED_6: { id: "PT_REDUCED_6", localId: "RED6", peppolCode: "AA", rate: 6, display: "VAT 6%", description: "6% VAT - reduced rate in Portugal", legalRef: null, legalText: () => "Reduced VAT rate (Autoridade Tributaria Portugal)", country: "PT", matcher: (id) => id === "RED6" },
    PT_REDUCED_13: { id: "PT_REDUCED_13", localId: "RED13", peppolCode: "AA", rate: 13, display: "VAT 13%", description: "13% VAT - reduced rate in Portugal", legalRef: null, legalText: () => "Reduced VAT rate (Autoridade Tributaria Portugal)", country: "PT", matcher: (id) => id === "RED13" },

    RO_STANDARD: { id: "RO_STANDARD", localId: "", peppolCode: "S", rate: 19, display: "VAT 19%", description: "19% VAT - standard rate in Romania", legalRef: null, legalText: () => "Standard VAT rate (ANAF Romania)", country: "RO", matcher: (id) => id === null || id === undefined || id === "" },
    RO_REDUCED_5: { id: "RO_REDUCED_5", localId: "RED5", peppolCode: "AA", rate: 5, display: "VAT 5%", description: "5% VAT - reduced rate in Romania", legalRef: null, legalText: () => "Reduced VAT rate (ANAF Romania)", country: "RO", matcher: (id) => id === "RED5" },
    RO_REDUCED_9: { id: "RO_REDUCED_9", localId: "RED9", peppolCode: "AA", rate: 9, display: "VAT 9%", description: "9% VAT - reduced rate in Romania", legalRef: null, legalText: () => "Reduced VAT rate (ANAF Romania)", country: "RO", matcher: (id) => id === "RED9" },

    SK_STANDARD: { id: "SK_STANDARD", localId: "", peppolCode: "S", rate: 20, display: "VAT 20%", description: "20% VAT - standard rate in Slovakia", legalRef: null, legalText: () => "Standard VAT rate (Financial Administration Slovakia)", country: "SK", matcher: (id) => id === null || id === undefined || id === "" },
    SK_REDUCED_10: { id: "SK_REDUCED_10", localId: "RED10", peppolCode: "AA", rate: 10, display: "VAT 10%", description: "10% VAT - reduced rate in Slovakia", legalRef: null, legalText: () => "Reduced VAT rate (Financial Administration Slovakia)", country: "SK", matcher: (id) => id === "RED10" },

    SI_STANDARD: { id: "SI_STANDARD", localId: "", peppolCode: "S", rate: 22, display: "VAT 22%", description: "22% VAT - standard rate in Slovenia", legalRef: null, legalText: () => "Standard VAT rate (FURS Slovenia)", country: "SI", matcher: (id) => id === null || id === undefined || id === "" },
    SI_REDUCED_5: { id: "SI_REDUCED_5", localId: "RED5", peppolCode: "AA", rate: 5, display: "VAT 5%", description: "5% VAT - reduced rate in Slovenia", legalRef: null, legalText: () => "Reduced VAT rate (FURS Slovenia)", country: "SI", matcher: (id) => id === "RED5" },
    SI_REDUCED_9_5: { id: "SI_REDUCED_9_5", localId: "RED9_5", peppolCode: "AA", rate: 9.5, display: "VAT 9.5%", description: "9.5% VAT - reduced rate in Slovenia", legalRef: null, legalText: () => "Reduced VAT rate (FURS Slovenia)", country: "SI", matcher: (id) => id === "RED9_5" || id === "RED9.5" },

    ES_STANDARD: { id: "ES_STANDARD", localId: "", peppolCode: "S", rate: 21, display: "VAT 21%", description: "21% VAT - standard rate in Spain", legalRef: null, legalText: () => "Standard VAT rate (Agencia Tributaria Spain)", country: "ES", matcher: (id) => id === null || id === undefined || id === "" },
    ES_REDUCED_4: { id: "ES_REDUCED_4", localId: "RED4", peppolCode: "AA", rate: 4, display: "VAT 4%", description: "4% VAT - reduced rate in Spain", legalRef: null, legalText: () => "Reduced VAT rate (Agencia Tributaria Spain)", country: "ES", matcher: (id) => id === "RED4" },
    ES_REDUCED_10: { id: "ES_REDUCED_10", localId: "RED10", peppolCode: "AA", rate: 10, display: "VAT 10%", description: "10% VAT - reduced rate in Spain", legalRef: null, legalText: () => "Reduced VAT rate (Agencia Tributaria Spain)", country: "ES", matcher: (id) => id === "RED10" },

    SE_STANDARD: { id: "SE_STANDARD", localId: "", peppolCode: "S", rate: 25, display: "VAT 25%", description: "25% VAT - standard rate in Sweden", legalRef: null, legalText: () => "Standard VAT rate (Skatteverket Sweden)", country: "SE", matcher: (id) => id === null || id === undefined || id === "" },
    SE_REDUCED_6: { id: "SE_REDUCED_6", localId: "RED6", peppolCode: "AA", rate: 6, display: "VAT 6%", description: "6% VAT - reduced rate in Sweden", legalRef: null, legalText: () => "Reduced VAT rate (Skatteverket Sweden)", country: "SE", matcher: (id) => id === "RED6" },
    SE_REDUCED_12: { id: "SE_REDUCED_12", localId: "RED12", peppolCode: "AA", rate: 12, display: "VAT 12%", description: "12% VAT - reduced rate in Sweden", legalRef: null, legalText: () => "Reduced VAT rate (Skatteverket Sweden)", country: "SE", matcher: (id) => id === "RED12" },

    US_STANDARD: {
        id: "US_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 0,
        display: "Sales Tax 0%",
        description: "No federal VAT in the United States; sales tax is state/local",
        legalRef: null,
        legalText: () => "US does not impose federal VAT",
        country: "US",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    US_SALES_TAX: {
        id: "US_SALES_TAX",
        localId: "SALES",
        peppolCode: "S",
        rate: 0,
        display: "Sales Tax",
        description: "Use item/location-specific state or local sales tax rate",
        legalRef: null,
        legalText: () => "State/local sales tax regime",
        country: "US",
        matcher: (id) => id === "SALES",
    },

    CA_STANDARD: {
        id: "CA_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 5,
        display: "GST 5%",
        description: "Federal GST in Canada",
        legalRef: null,
        legalText: () => "Canada federal GST standard rate",
        country: "CA",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    CA_ZERO: {
        id: "CA_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "GST/HST 0%",
        description: "Zero-rated supply in Canada",
        legalRef: null,
        legalText: () => "Canada zero-rated GST/HST supply",
        country: "CA",
        matcher: (id) => id === "ZERO",
    },
    CA_HST_ON_13: {
        id: "CA_HST_ON_13",
        localId: "HST13_ON",
        peppolCode: "S",
        rate: 13,
        display: "HST 13% (ON)",
        description: "Ontario Harmonized Sales Tax",
        legalRef: null,
        legalText: () => "Ontario HST rate",
        country: "CA",
        matcher: (id) => id === "HST13_ON" || id === "HST13",
    },
    CA_HST_NS_14: {
        id: "CA_HST_NS_14",
        localId: "HST14_NS",
        peppolCode: "S",
        rate: 14,
        display: "HST 14% (NS)",
        description: "Nova Scotia Harmonized Sales Tax",
        legalRef: null,
        legalText: () => "Nova Scotia HST rate",
        country: "CA",
        matcher: (id) => id === "HST14_NS" || id === "HST14",
    },
    CA_HST_NB_15: {
        id: "CA_HST_NB_15",
        localId: "HST15_NB",
        peppolCode: "S",
        rate: 15,
        display: "HST 15% (NB)",
        description: "New Brunswick Harmonized Sales Tax",
        legalRef: null,
        legalText: () => "New Brunswick HST rate",
        country: "CA",
        matcher: (id) => id === "HST15_NB",
    },
    CA_HST_NL_15: {
        id: "CA_HST_NL_15",
        localId: "HST15_NL",
        peppolCode: "S",
        rate: 15,
        display: "HST 15% (NL)",
        description: "Newfoundland and Labrador Harmonized Sales Tax",
        legalRef: null,
        legalText: () => "Newfoundland and Labrador HST rate",
        country: "CA",
        matcher: (id) => id === "HST15_NL",
    },
    CA_HST_PE_15: {
        id: "CA_HST_PE_15",
        localId: "HST15_PE",
        peppolCode: "S",
        rate: 15,
        display: "HST 15% (PE)",
        description: "Prince Edward Island Harmonized Sales Tax",
        legalRef: null,
        legalText: () => "Prince Edward Island HST rate",
        country: "CA",
        matcher: (id) => id === "HST15_PE",
    },

    GB_STANDARD: {
        id: "GB_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 20,
        display: "VAT 20%",
        description: "Standard VAT rate in the United Kingdom",
        legalRef: null,
        legalText: () => "UK standard VAT rate",
        country: "GB",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    GB_REDUCED_5: {
        id: "GB_REDUCED_5",
        localId: "RED5",
        peppolCode: "AA",
        rate: 5,
        display: "VAT 5%",
        description: "Reduced VAT rate in the United Kingdom",
        legalRef: null,
        legalText: () => "UK reduced VAT rate",
        country: "GB",
        matcher: (id) => id === "RED5",
    },
    GB_ZERO: {
        id: "GB_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in the United Kingdom",
        legalRef: null,
        legalText: () => "UK zero-rated VAT supply",
        country: "GB",
        matcher: (id) => id === "ZERO",
    },

    IL_STANDARD: {
        id: "IL_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 18,
        display: "VAT 18%",
        description: "Standard VAT rate in Israel",
        legalRef: null,
        legalText: () => "Israel standard VAT rate",
        country: "IL",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    IL_ZERO: {
        id: "IL_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Israel",
        legalRef: null,
        legalText: () => "Israel zero-rated VAT supply",
        country: "IL",
        matcher: (id) => id === "ZERO",
    },

    AE_STANDARD: {
        id: "AE_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 5,
        display: "VAT 5%",
        description: "Standard VAT rate in the UAE",
        legalRef: null,
        legalText: () => "UAE standard VAT rate",
        country: "AE",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    AE_ZERO: {
        id: "AE_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in the UAE",
        legalRef: null,
        legalText: () => "UAE zero-rated VAT supply",
        country: "AE",
        matcher: (id) => id === "ZERO",
    },

    SA_STANDARD: {
        id: "SA_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 15,
        display: "VAT 15%",
        description: "Standard VAT rate in Saudi Arabia",
        legalRef: null,
        legalText: () => "Saudi Arabia standard VAT rate",
        country: "SA",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    SA_ZERO: {
        id: "SA_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Saudi Arabia",
        legalRef: null,
        legalText: () => "Saudi Arabia zero-rated VAT supply",
        country: "SA",
        matcher: (id) => id === "ZERO",
    },

    QA_STANDARD: {
        id: "QA_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 0,
        display: "VAT 0%",
        description: "No VAT currently implemented in Qatar",
        legalRef: null,
        legalText: () => "Qatar has not implemented VAT yet",
        country: "QA",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    QA_FUTURE_5: {
        id: "QA_FUTURE_5",
        localId: "VAT5",
        peppolCode: "S",
        rate: 5,
        display: "VAT 5% (planned)",
        description: "Planned GCC VAT framework rate for Qatar",
        legalRef: null,
        legalText: () => "Qatar planned VAT regime placeholder",
        country: "QA",
        matcher: (id) => id === "VAT5",
    },

    KW_STANDARD: {
        id: "KW_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 0,
        display: "VAT 0%",
        description: "No VAT currently implemented in Kuwait",
        legalRef: null,
        legalText: () => "Kuwait has not implemented VAT yet",
        country: "KW",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    KW_FUTURE_5: {
        id: "KW_FUTURE_5",
        localId: "VAT5",
        peppolCode: "S",
        rate: 5,
        display: "VAT 5% (planned)",
        description: "Planned GCC VAT framework rate for Kuwait",
        legalRef: null,
        legalText: () => "Kuwait planned VAT regime placeholder",
        country: "KW",
        matcher: (id) => id === "VAT5",
    },

    IN_STANDARD: {
        id: "IN_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 18,
        display: "GST 18%",
        description: "India GST standard slab",
        legalRef: null,
        legalText: () => "India GST standard slab",
        country: "IN",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    IN_REDUCED_5: {
        id: "IN_REDUCED_5",
        localId: "RED5",
        peppolCode: "AA",
        rate: 5,
        display: "GST 5%",
        description: "India GST reduced slab",
        legalRef: null,
        legalText: () => "India GST reduced slab",
        country: "IN",
        matcher: (id) => id === "RED5",
    },
    IN_REDUCED_12: {
        id: "IN_REDUCED_12",
        localId: "RED12",
        peppolCode: "AA",
        rate: 12,
        display: "GST 12%",
        description: "India GST reduced slab",
        legalRef: null,
        legalText: () => "India GST reduced slab",
        country: "IN",
        matcher: (id) => id === "RED12",
    },
    IN_HIGH_28: {
        id: "IN_HIGH_28",
        localId: "HIGH28",
        peppolCode: "S",
        rate: 28,
        display: "GST 28%",
        description: "India GST highest slab",
        legalRef: null,
        legalText: () => "India GST highest slab",
        country: "IN",
        matcher: (id) => id === "HIGH28",
    },
    IN_ZERO: {
        id: "IN_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "GST 0%",
        description: "Zero-rated supply in India",
        legalRef: null,
        legalText: () => "India zero-rated GST supply",
        country: "IN",
        matcher: (id) => id === "ZERO",
    },

    BD_STANDARD: {
        id: "BD_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 15,
        display: "VAT 15%",
        description: "Standard VAT rate in Bangladesh",
        legalRef: null,
        legalText: () => "Bangladesh standard VAT rate",
        country: "BD",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    BD_ZERO: {
        id: "BD_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Bangladesh",
        legalRef: null,
        legalText: () => "Bangladesh zero-rated VAT supply",
        country: "BD",
        matcher: (id) => id === "ZERO",
    },

    SG_STANDARD: {
        id: "SG_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 9,
        display: "GST 9%",
        description: "Standard GST rate in Singapore",
        legalRef: null,
        legalText: () => "Singapore standard GST rate",
        country: "SG",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    SG_ZERO: {
        id: "SG_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "GST 0%",
        description: "Zero-rated supply in Singapore",
        legalRef: null,
        legalText: () => "Singapore zero-rated GST supply",
        country: "SG",
        matcher: (id) => id === "ZERO",
    },

    MY_STANDARD: {
        id: "MY_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 0,
        display: "SST (No VAT)",
        description: "Malaysia uses Sales and Service Tax (SST), not VAT/GST",
        legalRef: null,
        legalText: () => "Malaysia SST framework",
        country: "MY",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    MY_SST_8: {
        id: "MY_SST_8",
        localId: "SST8",
        peppolCode: "S",
        rate: 8,
        display: "SST 8%",
        description: "Malaysia service tax preset",
        legalRef: null,
        legalText: () => "Malaysia service tax preset",
        country: "MY",
        matcher: (id) => id === "SST8",
    },
    MY_SST_10: {
        id: "MY_SST_10",
        localId: "SST10",
        peppolCode: "S",
        rate: 10,
        display: "SST 10%",
        description: "Malaysia sales tax preset",
        legalRef: null,
        legalText: () => "Malaysia sales tax preset",
        country: "MY",
        matcher: (id) => id === "SST10",
    },

    ID_STANDARD: {
        id: "ID_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 12,
        display: "VAT 12%",
        description: "Standard VAT rate in Indonesia",
        legalRef: null,
        legalText: () => "Indonesia standard VAT rate",
        country: "ID",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    ID_ALT_11: {
        id: "ID_ALT_11",
        localId: "VAT11",
        peppolCode: "S",
        rate: 11,
        display: "VAT 11%",
        description: "Alternative/transitional VAT preset in Indonesia",
        legalRef: null,
        legalText: () => "Indonesia alternative VAT preset",
        country: "ID",
        matcher: (id) => id === "VAT11",
    },
    ID_ZERO: {
        id: "ID_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Indonesia",
        legalRef: null,
        legalText: () => "Indonesia zero-rated VAT supply",
        country: "ID",
        matcher: (id) => id === "ZERO",
    },

    VN_STANDARD: {
        id: "VN_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 10,
        display: "VAT 10%",
        description: "Standard VAT rate in Vietnam",
        legalRef: null,
        legalText: () => "Vietnam standard VAT rate",
        country: "VN",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    VN_REDUCED_8: {
        id: "VN_REDUCED_8",
        localId: "RED8",
        peppolCode: "AA",
        rate: 8,
        display: "VAT 8%",
        description: "Reduced VAT preset in Vietnam",
        legalRef: null,
        legalText: () => "Vietnam reduced VAT preset",
        country: "VN",
        matcher: (id) => id === "RED8",
    },
    VN_ZERO: {
        id: "VN_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Vietnam",
        legalRef: null,
        legalText: () => "Vietnam zero-rated VAT supply",
        country: "VN",
        matcher: (id) => id === "ZERO",
    },

    PH_STANDARD: {
        id: "PH_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 12,
        display: "VAT 12%",
        description: "Standard VAT rate in the Philippines",
        legalRef: null,
        legalText: () => "Philippines standard VAT rate",
        country: "PH",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    PH_ZERO: {
        id: "PH_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in the Philippines",
        legalRef: null,
        legalText: () => "Philippines zero-rated VAT supply",
        country: "PH",
        matcher: (id) => id === "ZERO",
    },

    TW_STANDARD: {
        id: "TW_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 5,
        display: "VAT 5%",
        description: "Standard VAT rate in Taiwan",
        legalRef: null,
        legalText: () => "Taiwan standard VAT rate",
        country: "TW",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    TW_ZERO: {
        id: "TW_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Taiwan",
        legalRef: null,
        legalText: () => "Taiwan zero-rated VAT supply",
        country: "TW",
        matcher: (id) => id === "ZERO",
    },

    HK_STANDARD: {
        id: "HK_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 0,
        display: "GST 0%",
        description: "No VAT/GST currently implemented in Hong Kong",
        legalRef: null,
        legalText: () => "Hong Kong has no VAT/GST regime",
        country: "HK",
        matcher: (id) => id === null || id === undefined || id === "",
    },

    TH_STANDARD: {
        id: "TH_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 7,
        display: "VAT 7%",
        description: "Standard VAT rate in Thailand",
        legalRef: null,
        legalText: () => "Thailand standard VAT rate",
        country: "TH",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    TH_ZERO: {
        id: "TH_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Thailand",
        legalRef: null,
        legalText: () => "Thailand zero-rated VAT supply",
        country: "TH",
        matcher: (id) => id === "ZERO",
    },

    KH_STANDARD: {
        id: "KH_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 10,
        display: "VAT 10%",
        description: "Standard VAT rate in Cambodia",
        legalRef: null,
        legalText: () => "Cambodia standard VAT rate",
        country: "KH",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    KH_ZERO: {
        id: "KH_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Cambodia",
        legalRef: null,
        legalText: () => "Cambodia zero-rated VAT supply",
        country: "KH",
        matcher: (id) => id === "ZERO",
    },

    ZA_STANDARD: {
        id: "ZA_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 15,
        display: "VAT 15%",
        description: "Standard VAT rate in South Africa",
        legalRef: null,
        legalText: () => "South Africa standard VAT rate",
        country: "ZA",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    ZA_ZERO: {
        id: "ZA_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in South Africa",
        legalRef: null,
        legalText: () => "South Africa zero-rated VAT supply",
        country: "ZA",
        matcher: (id) => id === "ZERO",
    },

    KE_STANDARD: {
        id: "KE_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 16,
        display: "VAT 16%",
        description: "Standard VAT rate in Kenya",
        legalRef: null,
        legalText: () => "Kenya standard VAT rate",
        country: "KE",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    KE_ZERO: {
        id: "KE_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Kenya",
        legalRef: null,
        legalText: () => "Kenya zero-rated VAT supply",
        country: "KE",
        matcher: (id) => id === "ZERO",
    },

    NG_STANDARD: {
        id: "NG_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 7.5,
        display: "VAT 7.5%",
        description: "Standard VAT rate in Nigeria",
        legalRef: null,
        legalText: () => "Nigeria standard VAT rate",
        country: "NG",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    NG_ZERO: {
        id: "NG_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Nigeria",
        legalRef: null,
        legalText: () => "Nigeria zero-rated VAT supply",
        country: "NG",
        matcher: (id) => id === "ZERO",
    },

    EG_STANDARD: {
        id: "EG_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 14,
        display: "VAT 14%",
        description: "Standard VAT rate in Egypt",
        legalRef: null,
        legalText: () => "Egypt standard VAT rate",
        country: "EG",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    EG_ZERO: {
        id: "EG_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Egypt",
        legalRef: null,
        legalText: () => "Egypt zero-rated VAT supply",
        country: "EG",
        matcher: (id) => id === "ZERO",
    },

    MA_STANDARD: {
        id: "MA_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 20,
        display: "VAT 20%",
        description: "Standard VAT rate in Morocco",
        legalRef: null,
        legalText: () => "Morocco standard VAT rate",
        country: "MA",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    MA_REDUCED_10: {
        id: "MA_REDUCED_10",
        localId: "RED10",
        peppolCode: "AA",
        rate: 10,
        display: "VAT 10%",
        description: "Reduced VAT rate in Morocco",
        legalRef: null,
        legalText: () => "Morocco reduced VAT rate",
        country: "MA",
        matcher: (id) => id === "RED10",
    },
    MA_ZERO: {
        id: "MA_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Morocco",
        legalRef: null,
        legalText: () => "Morocco zero-rated VAT supply",
        country: "MA",
        matcher: (id) => id === "ZERO",
    },

    GH_STANDARD: {
        id: "GH_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 15,
        display: "VAT 15%",
        description: "Standard VAT rate in Ghana",
        legalRef: null,
        legalText: () => "Ghana VAT component (excluding NHIL/GETFund levies)",
        country: "GH",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    GH_COMBINED_20: {
        id: "GH_COMBINED_20",
        localId: "VAT20",
        peppolCode: "S",
        rate: 20,
        display: "VAT+Levy 20%",
        description: "Ghana effective VAT stack: VAT 15% + NHIL 2.5% + GETFund 2.5%",
        legalRef: null,
        legalText: () => "Ghana combined effective VAT/levy rate",
        country: "GH",
        matcher: (id) => id === "VAT20",
    },
    GH_ZERO: {
        id: "GH_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Ghana",
        legalRef: null,
        legalText: () => "Ghana zero-rated VAT supply",
        country: "GH",
        matcher: (id) => id === "ZERO",
    },

    TN_STANDARD: {
        id: "TN_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 19,
        display: "VAT 19%",
        description: "Standard VAT rate in Tunisia",
        legalRef: null,
        legalText: () => "Tunisia standard VAT rate",
        country: "TN",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    TN_REDUCED_13: {
        id: "TN_REDUCED_13",
        localId: "RED13",
        peppolCode: "AA",
        rate: 13,
        display: "VAT 13%",
        description: "Reduced VAT rate in Tunisia",
        legalRef: null,
        legalText: () => "Tunisia reduced VAT rate",
        country: "TN",
        matcher: (id) => id === "RED13",
    },
    TN_REDUCED_7: {
        id: "TN_REDUCED_7",
        localId: "RED7",
        peppolCode: "AA",
        rate: 7,
        display: "VAT 7%",
        description: "Reduced VAT rate in Tunisia",
        legalRef: null,
        legalText: () => "Tunisia reduced VAT rate",
        country: "TN",
        matcher: (id) => id === "RED7",
    },
    TN_ZERO: {
        id: "TN_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Tunisia",
        legalRef: null,
        legalText: () => "Tunisia zero-rated VAT supply",
        country: "TN",
        matcher: (id) => id === "ZERO",
    },

    DZ_STANDARD: {
        id: "DZ_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 19,
        display: "VAT 19%",
        description: "Standard VAT rate in Algeria",
        legalRef: null,
        legalText: () => "Algeria standard VAT rate",
        country: "DZ",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    DZ_REDUCED_9: {
        id: "DZ_REDUCED_9",
        localId: "RED9",
        peppolCode: "AA",
        rate: 9,
        display: "VAT 9%",
        description: "Reduced VAT rate in Algeria",
        legalRef: null,
        legalText: () => "Algeria reduced VAT rate",
        country: "DZ",
        matcher: (id) => id === "RED9",
    },
    DZ_ZERO: {
        id: "DZ_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Algeria",
        legalRef: null,
        legalText: () => "Algeria zero-rated VAT supply",
        country: "DZ",
        matcher: (id) => id === "ZERO",
    },

    MU_STANDARD: {
        id: "MU_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 15,
        display: "VAT 15%",
        description: "Standard VAT rate in Mauritius",
        legalRef: null,
        legalText: () => "Mauritius standard VAT rate",
        country: "MU",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    MU_ZERO: {
        id: "MU_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Mauritius",
        legalRef: null,
        legalText: () => "Mauritius zero-rated VAT supply",
        country: "MU",
        matcher: (id) => id === "ZERO",
    },

    BW_STANDARD: {
        id: "BW_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 14,
        display: "VAT 14%",
        description: "Standard VAT rate in Botswana",
        legalRef: null,
        legalText: () => "Botswana standard VAT rate",
        country: "BW",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    BW_ZERO: {
        id: "BW_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Botswana",
        legalRef: null,
        legalText: () => "Botswana zero-rated VAT supply",
        country: "BW",
        matcher: (id) => id === "ZERO",
    },

    NA_STANDARD: {
        id: "NA_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 15,
        display: "VAT 15%",
        description: "Standard VAT rate in Namibia",
        legalRef: null,
        legalText: () => "Namibia standard VAT rate",
        country: "NA",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    NA_ZERO: {
        id: "NA_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Namibia",
        legalRef: null,
        legalText: () => "Namibia zero-rated VAT supply",
        country: "NA",
        matcher: (id) => id === "ZERO",
    },

    SC_STANDARD: {
        id: "SC_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 15,
        display: "VAT 15%",
        description: "Standard VAT rate in Seychelles",
        legalRef: null,
        legalText: () => "Seychelles standard VAT rate",
        country: "SC",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    SC_ZERO: {
        id: "SC_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Seychelles",
        legalRef: null,
        legalText: () => "Seychelles zero-rated VAT supply",
        country: "SC",
        matcher: (id) => id === "ZERO",
    },

    RW_STANDARD: {
        id: "RW_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 18,
        display: "VAT 18%",
        description: "Standard VAT rate in Rwanda",
        legalRef: null,
        legalText: () => "Rwanda standard VAT rate",
        country: "RW",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    RW_ZERO: {
        id: "RW_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Rwanda",
        legalRef: null,
        legalText: () => "Rwanda zero-rated VAT supply",
        country: "RW",
        matcher: (id) => id === "ZERO",
    },

    UG_STANDARD: {
        id: "UG_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 18,
        display: "VAT 18%",
        description: "Standard VAT rate in Uganda",
        legalRef: null,
        legalText: () => "Uganda standard VAT rate",
        country: "UG",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    UG_ZERO: {
        id: "UG_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Uganda",
        legalRef: null,
        legalText: () => "Uganda zero-rated VAT supply",
        country: "UG",
        matcher: (id) => id === "ZERO",
    },

    CI_STANDARD: {
        id: "CI_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 18,
        display: "VAT 18%",
        description: "Standard VAT rate in Cote d'Ivoire",
        legalRef: null,
        legalText: () => "Cote d'Ivoire standard VAT rate",
        country: "CI",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    CI_ZERO: {
        id: "CI_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Cote d'Ivoire",
        legalRef: null,
        legalText: () => "Cote d'Ivoire zero-rated VAT supply",
        country: "CI",
        matcher: (id) => id === "ZERO",
    },

    SN_STANDARD: {
        id: "SN_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 18,
        display: "VAT 18%",
        description: "Standard VAT rate in Senegal",
        legalRef: null,
        legalText: () => "Senegal standard VAT rate",
        country: "SN",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    SN_ZERO: {
        id: "SN_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Senegal",
        legalRef: null,
        legalText: () => "Senegal zero-rated VAT supply",
        country: "SN",
        matcher: (id) => id === "ZERO",
    },

    CM_STANDARD: {
        id: "CM_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 19.25,
        display: "VAT 19.25%",
        description: "Standard VAT rate in Cameroon",
        legalRef: null,
        legalText: () => "Cameroon standard VAT rate",
        country: "CM",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    CM_ZERO: {
        id: "CM_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Cameroon",
        legalRef: null,
        legalText: () => "Cameroon zero-rated VAT supply",
        country: "CM",
        matcher: (id) => id === "ZERO",
    },

    TZ_STANDARD: {
        id: "TZ_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 18,
        display: "VAT 18%",
        description: "Standard VAT rate in Tanzania",
        legalRef: null,
        legalText: () => "Tanzania standard VAT rate",
        country: "TZ",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    TZ_ZERO: {
        id: "TZ_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Tanzania",
        legalRef: null,
        legalText: () => "Tanzania zero-rated VAT supply",
        country: "TZ",
        matcher: (id) => id === "ZERO",
    },

    ZM_STANDARD: {
        id: "ZM_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 16,
        display: "VAT 16%",
        description: "Standard VAT rate in Zambia",
        legalRef: null,
        legalText: () => "Zambia standard VAT rate",
        country: "ZM",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    ZM_ZERO: {
        id: "ZM_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Zambia",
        legalRef: null,
        legalText: () => "Zambia zero-rated VAT supply",
        country: "ZM",
        matcher: (id) => id === "ZERO",
    },

    ET_STANDARD: {
        id: "ET_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 15,
        display: "VAT 15%",
        description: "Standard VAT rate in Ethiopia",
        legalRef: null,
        legalText: () => "Ethiopia standard VAT rate",
        country: "ET",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    ET_ZERO: {
        id: "ET_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Ethiopia",
        legalRef: null,
        legalText: () => "Ethiopia zero-rated VAT supply",
        country: "ET",
        matcher: (id) => id === "ZERO",
    },

    AO_STANDARD: {
        id: "AO_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 14,
        display: "VAT 14%",
        description: "Standard VAT rate in Angola",
        legalRef: null,
        legalText: () => "Angola standard VAT rate",
        country: "AO",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    AO_ZERO: {
        id: "AO_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Angola",
        legalRef: null,
        legalText: () => "Angola zero-rated VAT supply",
        country: "AO",
        matcher: (id) => id === "ZERO",
    },

    MZ_STANDARD: {
        id: "MZ_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 16,
        display: "VAT 16%",
        description: "Standard VAT rate in Mozambique",
        legalRef: null,
        legalText: () => "Mozambique standard VAT rate",
        country: "MZ",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    MZ_ZERO: {
        id: "MZ_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Mozambique",
        legalRef: null,
        legalText: () => "Mozambique zero-rated VAT supply",
        country: "MZ",
        matcher: (id) => id === "ZERO",
    },

    CD_STANDARD: {
        id: "CD_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 16,
        display: "VAT 16%",
        description: "Standard VAT rate in DR Congo",
        legalRef: null,
        legalText: () => "DR Congo standard VAT rate",
        country: "CD",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    CD_ZERO: {
        id: "CD_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in DR Congo",
        legalRef: null,
        legalText: () => "DR Congo zero-rated VAT supply",
        country: "CD",
        matcher: (id) => id === "ZERO",
    },

    SD_STANDARD: {
        id: "SD_STANDARD",
        localId: "",
        peppolCode: "S",
        rate: 17,
        display: "VAT 17%",
        description: "Standard VAT rate in Sudan",
        legalRef: null,
        legalText: () => "Sudan standard VAT rate",
        country: "SD",
        matcher: (id) => id === null || id === undefined || id === "",
    },
    SD_ZERO: {
        id: "SD_ZERO",
        localId: "ZERO",
        peppolCode: "Z",
        rate: 0,
        display: "VAT 0%",
        description: "Zero-rated supply in Sudan",
        legalRef: null,
        legalText: () => "Sudan zero-rated VAT supply",
        country: "SD",
        matcher: (id) => id === "ZERO",
    },

    EU_INTRA_COMMUNITY: {
        id: "EU_INTRA_COMMUNITY",
        localId: "EU_IC",
        peppolCode: "K",
        rate: 0,
        display: "VAT 0%",
        description: "0% VAT - Intra-community supply within EU",
        legalRef: "138",
        legalText: () => "Intra-community supply (Art. 138 EU VAT Directive)",
        country: "EU",
        requiresVAT: true,
        matcher: null,
    },
    EU_EXPORT: {
        id: "EU_EXPORT",
        localId: "EXPORT",
        peppolCode: "G",
        rate: 0,
        display: "VAT 0%",
        legalRef: null,
        legalText: () => "Export outside EU",
        country: null,
        matcher: null,
    },
};
